const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Sin,
		C3.Behaviors.MoveTo,
		C3.Plugins.Audio,
		C3.Behaviors.TileMovement.Cnds.IsMovingDirection,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.ObjectUIDExists,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play
	];
};
self.C3_JsPropNameTable = [
	{Cristal: 0},
	{Solid: 0},
	{Brick: 0},
	{Brick_2: 0},
	{tijoloazul: 0},
	{Caverna: 0},
	{DarkCidade_: 0},
	{bloco: 0},
	{Fade: 0},
	{StorylineText: 0},
	{Cristal2: 0},
	{Cristal3: 0},
	{Cristal4: 0},
	{objeto1: 0},
	{Item1: 0},
	{Item2: 0},
	{Item3: 0},
	{Item4: 0},
	{bloco2: 0},
	{TileMovement: 0},
	{jogador: 0},
	{Collect: 0},
	{MiniCristal: 0},
	{Texto2: 0},
	{Counter: 0},
	{texto: 0},
	{objeto2: 0},
	{Sine: 0},
	{inimigo: 0},
	{GameOverTexto: 0},
	{MoveTo: 0},
	{inimigo1: 0},
	{inimigo2: 0},
	{TextoDeBaixo: 0},
	{Sprite: 0},
	{Áudio: 0},
	{vidas: 0}
];

self.InstanceType = {
	Cristal: class extends self.ISpriteInstance {},
	Brick: class extends self.ISpriteInstance {},
	Brick_2: class extends self.ISpriteInstance {},
	tijoloazul: class extends self.ITiledBackgroundInstance {},
	Caverna: class extends self.ISpriteInstance {},
	DarkCidade_: class extends self.ISpriteInstance {},
	bloco: class extends self.ITiledBackgroundInstance {},
	StorylineText: class extends self.ITextInstance {},
	Cristal2: class extends self.ISpriteInstance {},
	Cristal3: class extends self.ISpriteInstance {},
	Cristal4: class extends self.ISpriteInstance {},
	objeto1: class extends self.ISpriteInstance {},
	Item1: class extends self.ISpriteInstance {},
	Item2: class extends self.ISpriteInstance {},
	Item3: class extends self.ISpriteInstance {},
	Item4: class extends self.ISpriteInstance {},
	bloco2: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	MiniCristal: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	texto: class extends self.ITextInstance {},
	objeto2: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	GameOverTexto: class extends self.ITextInstance {},
	inimigo1: class extends self.ISpriteInstance {},
	inimigo2: class extends self.ISpriteInstance {},
	TextoDeBaixo: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {}
}